name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA (no code signing)
        run: flutter build ios --no-codesign

      - name: Zip IPA folder
        run: |
          cd build/ios/iphoneos
          zip -r app.ipa Payload/

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kravasign-iOS-Build
          path: build/ios/iphoneos/app.ipa
