name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (Release + Obfuscation)
        run: flutter build ios --release --obfuscate --split-debug-info=build/symbols --no-codesign

      - name: Create IPA folder structure
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/

      - name: Zip to IPA
        run: zip -r Kravasign.ipa Payload/

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kravasign-iOS-Build
          path: Kravasign.ipa
