name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App (release, no code sign)
        run: flutter build ios --release --obfuscate --split-debug-info=build/symbols --no-codesign

      - name: Strip Flutter.framework architectures
        run: |
          FILE=build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter
          echo "Before:"
          lipo -info
